# Generated by Django 6.1.1 on 2026-09-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('families', '0003_persian_admin_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته', 'verbose_name_plural': 'دسته\u200cها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=20, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='families.familygroup', verbose_name='خانواده'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=100, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='پیش\u200cفرض'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
