# Generated by Django 6.1.1 on 2026-09-11 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familygroup',
            options={'verbose_name': 'خانواده', 'verbose_name_plural': 'خانواده\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='familymembership',
            options={'verbose_name': 'عضو خانواده', 'verbose_name_plural': 'اعضای خانواده'},
        ),
        migrations.AlterField(
            model_name='familygroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='familygroup',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام خانواده'),
        ),
        migrations.AlterField(
            model_name='familymembership',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='families.familygroup', verbose_name='خانواده'),
        ),
        migrations.AlterField(
            model_name='familymembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان عضویت'),
        ),
        migrations.AlterField(
            model_name='familymembership',
            name='role',
            field=models.CharField(choices=[('owner', 'مدیر خانواده'), ('member', 'عضو')], default='member', max_length=20, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='familymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
