# Generated by Django 6.1.1 on 2026-09-25 04:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0003_persian_admin_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceHealth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(max_length=64, verbose_name="شناسه\u200cی گوشی"),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="نسخه\u200cی برنامه"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("ok", "سالم"),
                            ("warn", "نیاز به بررسی"),
                            ("bad", "مشکل"),
                        ],
                        max_length=8,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="خلاصه"),
                ),
                (
                    "reported_at",
                    models.DateTimeField(verbose_name="زمانِ گزارش (گوشی)"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمانِ دریافت"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_health",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "سلامتِ گوشی",
                "verbose_name_plural": "سلامتِ گوشی\u200cها",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "device_id"), name="unique_device_health"
                    )
                ],
            },
        ),
    ]
