# Generated by Django 6.1.1 on 2026-09-11 15:37

import apps.users.phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(error_messages={'unique': 'کاربری با این شماره موبایل از قبل هست.'}, help_text='با همین شماره و رمز وارد اپ می\u200cشود؛ مثلاً 09121234567', max_length=11, null=True, unique=True, validators=[apps.users.phone.validate_mobile], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='همین نام در اپ کنار تراکنش\u200cها دیده می\u200cشود؛ مثلاً «بابا»', max_length=150, verbose_name='نام'),
        ),
    ]
