# Generated by Django 6.1.1 on 2026-09-10 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('families', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=10)),
                ('amount_rial', models.BigIntegerField(blank=True, null=True)),
                ('balance_after_rial', models.BigIntegerField(blank=True, null=True)),
                ('raw_amount', models.CharField(blank=True, max_length=32)),
                ('raw_unit', models.CharField(default='rial', max_length=8)),
                ('counterparty', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('transfer_group', models.UUIDField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(choices=[('sms', 'SMS'), ('manual', 'Manual'), ('notification', 'Notification')], default='sms', max_length=20)),
                ('source_message_hash', models.CharField(blank=True, max_length=64)),
                ('device_id', models.CharField(blank=True, max_length=64)),
                ('needs_review', models.BooleanField(default=False)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('client_created_at', models.DateTimeField(blank=True, null=True)),
                ('server_received_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.bankaccount')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.card')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='categories.category')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='families.familygroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['family', 'transaction_date'], name='transaction_family__1178b3_idx'), models.Index(fields=['family', 'owner'], name='transaction_family__6a90bb_idx'), models.Index(fields=['family', 'category'], name='transaction_family__dc934d_idx'), models.Index(fields=['family', 'card'], name='transaction_family__8d1807_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_message_hash', ''), _negated=True), fields=('family', 'source_message_hash'), name='unique_family_source_hash')],
            },
        ),
    ]
