# Generated by Django 6.1.1 on 2026-09-11 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_captured_by(apps, schema_editor):
    # تا این نسخه، فرستنده‌ی تراکنش همان صاحبش بود.
    Transaction = apps.get_model("transactions", "Transaction")
    Transaction.objects.filter(captured_by__isnull=True).update(captured_by=F("owner"))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('families', '0002_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='allocations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='transaction',
            name='client_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='person_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['family', 'updated_at'], name='transaction_family__b209ca_idx'),
        ),
        migrations.RunPython(backfill_captured_by, migrations.RunPython.noop),
    ]
