# Generated by Django 6.1.1 on 2026-09-11 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_persian_admin_labels'),
        ('categories', '0002_persian_admin_labels'),
        ('families', '0003_persian_admin_labels'),
        ('transactions', '0002_owner_capture_allocations_softdelete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش\u200cها'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.bankaccount', verbose_name='حساب'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='allocations',
            field=models.JSONField(blank=True, default=list, verbose_name='دسته\u200cها'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_rial',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ (ریال)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after_rial',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='مانده بعد (ریال)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='بانک'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_transactions', to=settings.AUTH_USER_MODEL, verbose_name='پیامک روی گوشیِ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.card', verbose_name='کارت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, verbose_name='۴ رقم کارت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='categories.category', verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت روی گوشی'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین ویرایش روی گوشی'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterparty',
            field=models.CharField(blank=True, max_length=200, verbose_name='طرف حساب / بابت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='device_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='شناسه\u200cی گوشی'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='families.familygroup', verbose_name='خانواده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='نامعتبر (حذف\u200cشده)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه'), ('transfer', 'انتقال')], max_length=10, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='منتظر بازبینی'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='صاحب کارت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='person_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام صاحب'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='raw_amount',
            field=models.CharField(blank=True, max_length=32, verbose_name='مبلغ خام'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='raw_unit',
            field=models.CharField(default='rial', max_length=8, verbose_name='واحد خام'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='server_received_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان رسیدن به سرور'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('sms', 'پیامک'), ('manual', 'دستی'), ('notification', 'اعلان')], default='sms', max_length=20, verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_message_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='اثرانگشت پیامک'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تراکنش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='برچسب کارت'),
        ),
    ]
