# Generated by Django 6.1.1 on 2026-09-26 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0004_device_health'),
        ('users', '0002_phone_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enabled', models.BooleanField(default=False, verbose_name='نسخه\u200cی ۲ روشن')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخِ شروع')),
                ('setup_done', models.BooleanField(default=False, verbose_name='راهنما دیده شده')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیماتِ دفتر',
                'verbose_name_plural': 'تنظیماتِ دفتر (نسخه\u200cی ۲)',
            },
        ),
        migrations.CreateModel(
            name='LedgerCheckpoint',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ویرایش روی گوشی')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('account_id', models.UUIDField(verbose_name='حساب (کیف)')),
                ('at', models.DateTimeField(verbose_name='زمان')),
                ('balance_rial', models.BigIntegerField(verbose_name='موجودی (ریال)')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='یادداشت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='families.familygroup', verbose_name='خانواده')),
            ],
            options={
                'verbose_name': 'نقطه\u200cی مانده',
                'verbose_name_plural': 'نقطه\u200cهای مانده (نسخه\u200cی ۲)',
                'indexes': [models.Index(fields=['family', 'created_by', 'updated_at'], name='ledger_ledg_family__9f1614_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ویرایش روی گوشی')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('account_id', models.UUIDField(verbose_name='حساب (کیف)')),
                ('kind', models.CharField(choices=[('income', 'واریز'), ('expense', 'برداشت')], max_length=10, verbose_name='نوع')),
                ('is_transfer', models.BooleanField(default=False, verbose_name='انتقال بینِ حساب\u200cهای خودم')),
                ('transfer_pair_id', models.UUIDField(blank=True, null=True)),
                ('amount_rial', models.BigIntegerField(verbose_name='مبلغ (ریال)')),
                ('occurred_at', models.DateTimeField(verbose_name='زمان')),
                ('bank_balance_after', models.BigIntegerField(blank=True, null=True, verbose_name='مانده\u200cی بانک بعد از آن')),
                ('source', models.CharField(choices=[('sms', 'پیامک'), ('manual', 'دستی'), ('adjustment', 'اصلاح')], max_length=12, verbose_name='منبع')),
                ('sms_key', models.CharField(blank=True, max_length=100, verbose_name='کلیدِ پیامک')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='یادداشت')),
                ('categories', models.JSONField(blank=True, default=list, verbose_name='دسته\u200cها')),
                ('created_by_device', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='families.familygroup', verbose_name='خانواده')),
            ],
            options={
                'verbose_name': 'تراکنشِ دفتر',
                'verbose_name_plural': 'تراکنش\u200cهای دفتر (نسخه\u200cی ۲)',
                'indexes': [models.Index(fields=['family', 'created_by', 'updated_at'], name='ledger_ledg_family__0de39e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmsDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='کلیدِ پیامک')),
                ('content_hash', models.CharField(max_length=64, verbose_name='اثرانگشتِ محتوا')),
                ('received_at', models.DateTimeField(verbose_name='زمانِ رسیدن')),
                ('status', models.CharField(choices=[('pending', 'منتظر'), ('accepted', 'ثبت'), ('rejected', 'رد')], max_length=10, verbose_name='تصمیم')),
                ('reject_reason', models.CharField(blank=True, max_length=12, verbose_name='دلیلِ رد')),
                ('entry_id', models.UUIDField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='زمانِ تصمیم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تصمیمِ پیامک',
                'verbose_name_plural': 'تصمیم\u200cهای پیامک (نسخه\u200cی ۲)',
                'indexes': [models.Index(fields=['user', 'updated_at'], name='ledger_smsd_user_id_5b17c6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_decision_per_user')],
            },
        ),
    ]
