# Generated by Django 6.1.1 on 2026-09-11 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('families', '0003_persian_admin_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'حساب بانکی', 'verbose_name_plural': 'حساب\u200cهای بانکی'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'کارت', 'verbose_name_plural': 'کارت\u200cها'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number_masked',
            field=models.CharField(blank=True, max_length=32, verbose_name='شماره حساب (ماسک\u200cشده)'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(default='checking', max_length=30, verbose_name='نوع حساب'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='شناسه\u200cی بانک'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='بانک'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(default='IRR', max_length=3, verbose_name='ارز'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='families.familygroup', verbose_name='خانواده'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='صاحب'),
        ),
        migrations.AlterField(
            model_name='card',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.bankaccount', verbose_name='حساب'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='برچسب'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_last4',
            field=models.CharField(max_length=4, verbose_name='۴ رقم آخر کارت'),
        ),
    ]
