# Generated by Django 6.1.1 on 2026-09-14 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_persian_admin_labels'),
        ('families', '0003_persian_admin_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='نام صاحب')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='برچسب')),
                ('bank_id', models.CharField(blank=True, max_length=50, verbose_name='شناسه\u200cی بانک')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='۴ رقم کارت')),
                ('account_ref', models.CharField(blank=True, max_length=32, verbose_name='شماره حساب')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف\u200cشده')),
                ('client_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ویرایش روی گوشی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets_created', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='families.familygroup', verbose_name='خانواده')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='صاحب')),
            ],
            options={
                'verbose_name': 'کیف (کارت/حساب)',
                'verbose_name_plural': 'کیف\u200cها (کارت/حساب)',
                'indexes': [models.Index(fields=['family', 'updated_at'], name='accounts_wa_family__a2d749_idx'), models.Index(fields=['family', 'owner'], name='accounts_wa_family__a3f023_idx')],
            },
        ),
    ]
