# Generated by Django 6.1.1 on 2026-09-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='کنارگذاشته'),
        ),
    ]
