# Generated by Django 6.1.1 on 2026-09-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
        ('categories', '0002_persian_admin_labels'),
        ('families', '0003_persian_admin_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'بودجه', 'verbose_name_plural': 'بودجه\u200cها'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='categories.category', verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='families.familygroup', verbose_name='خانواده'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='limit_rial',
            field=models.BigIntegerField(verbose_name='سقف (ریال)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('monthly', 'ماهانه'), ('weekly', 'هفتگی')], default='monthly', max_length=10, verbose_name='دوره'),
        ),
    ]
