# Generated by Django 6.1.1 on 2026-09-14 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_persian_admin_labels'),
        ('families', '0003_persian_admin_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_category_period',
        ),
        migrations.AddField(
            model_name='budget',
            name='category_name',
            field=models.CharField(default='', max_length=100, verbose_name='نام دسته'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='client_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین ویرایش روی گوشی'),
        ),
        migrations.AddField(
            model_name='budget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_created', to=settings.AUTH_USER_MODEL, verbose_name='سازنده'),
        ),
        migrations.AddField(
            model_name='budget',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف\u200cشده'),
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['family', 'updated_at'], name='budgets_bud_family__def42d_idx'),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
    ]
